package genx

import (
	"github.com/stretchr/testify/assert"
	"strconv"
	"testing"
)

var result = `//Code generated by genx. DO NOT EDIT.

package main

import (
	fmt "fmt"
)

func main() {
	fmt.Println("hello world")
}
`

func TestGen(t *testing.T) {
	file := NewGeneratedFile("main.go", "main")
	file.P(Comments("Code generated by genx. DO NOT EDIT."))
	file.P()
	file.P("package main")
	file.P()
	file.P("func main() {")
	file.P(GoImportPath("fmt").Ident("Println"), "(", strconv.Quote("hello world"), ")")
	file.P("}")
	content, err := file.Content()
	if err != nil {
		t.Fatal(err)
	}
	assert.Equal(t, result, string(content))
}
